apiVersion: v1
kind: Namespace
metadata:
  name: ws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: townify-ws
  namespace: ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
        - name: ws-server
          image: mohammedayad10/townify-ws:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3008
          resources:
            requests:
              cpu: "1000m"
            limits:
              cpu: "1000m"
          env:
            - name: UPSTASH_REDIS_REST_URL
              valueFrom:
                secretKeyRef:
                  name: ws-secret
                  key: UPSTASH_REDIS_REST_URL

            - name: UPSTASH_REDIS_REST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ws-secret
                  key: UPSTASH_REDIS_REST_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: ws
spec:
  selector:
    app: ws-server
  ports:
    - name: ws-service
      protocol: TCP
      port: 3008
      targetPort: 3008
  type: ClusterIP
