apiVersion: v1
kind: Namespace
metadata:
  name: notification

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: townify-notification
  namespace: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: townify-notification
  template:
    metadata:
      labels:
        app: townify-notification
    spec:
      containers:
        - name: notification-server
          image: mohammedayad10/townify-notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
          resources:
            request:
              cpu: "1000m"
            limit:
              cpu: "1000m"
          env:
            - name: REDIS_PUBSUB_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: REDIS_PUBSUB_URL

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
spec:
  selector:
    app: townify-notification
  ports:
    - name: notification-service
      protocol: TCP
      port: 3010
      targetPort: 3010
  type: ClusterIP
