---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-secret
  namespace: notification
spec:
  encryptedData:
    REDIS_PUBSUB_URL: AgCMU5d01xcHxc4pVSiZK8kbTV9wJu85C4VV/rqARh4zRMeiMGEpxqniSzMYllh+zg41pR9Gpm+le8BOWPH75DM27Yc9AIKfXmNfMZtHm+p92oLxBdtM28OMoxkOweGlLr3UY0rNXbpla38ke1OlIFDtS+MBrOxMx5qvTAcFXi2W6QloE720c2LnYOoIXjv7OVjzzJYVIgnECKTs/0bL8Mp+1MHur2uR7Z+Ot8aKO9CxhqbEy0uehrldyvF5v3f5sbR8JA9Y5KnHORFsmb7FTc1yxeWb0AOSpVSB/wWY2DaHMmGLFlu3rRJA53xmZKoHaX3b+QhOAXxNZFRHH/bnkkFloovwOKL95DOiOQVGoL5Eduvw+1xB6DEdrNOeUz6fKJHIVNRbYbRk02PJyCG8cRELYUWGh4nHWrN29r+B99qiR/jtISjGCGPoYWa7o2S473JEU8DKWRUy04R66wdeC/6PaIigRN5a7O6WI9DyJ0Pnt+d1QJTf/j28YzUD31/YD+er5+PWtVATOdsvzG9GPncZnEc+ucoipc6d6Id6RVN0ztAh4cEbr/FNUsMAPx377DdqkYwMhgJebRPcfBunBkpYMWWDWygJHqr4tyRvLIdVGbW8/99uax5/DJWcmpSM/5MjyNRMYEpXKD83/jW3OQrfiGRxQa0XiF7yMV/jtWz7eZkg3f5zLSXvy/2l/Quf/9KMhL5mmD4xXC+dUJJvf2U8GQyuy0E7FMTpBT3X5O9qC79U8GrxcHnASlXfq2kc4Ek4xbUN6CLUUO4hHr53MlRNf/raEKIXQWOBJ+77NzlrhzxQeW+xnclyCl58jx1oSBkOpyCQrf5G4PW3chYYAcU=
  template:
    metadata:
      name: notification-secret
      namespace: notification
